version: 2
updates:
  - package-ecosystem: gradle
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: "/chat-server"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"          
  - package-ecosystem: docker-compose
    directory: "/chat-server"
    schedule:
      interval: weekly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
