name: chat-server

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/ci-chat-server.yml
      - chat-server/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/ci-chat-server.yml
      - chat-server/**

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
          cache-dependency-path: chat-server/build.gradle.kts

      - name: Build
        working-directory: chat-server
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: ./gradlew build --no-daemon --info